FROM tiangolo/nginx-rtmp

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /www/
#COPY live_session.html 'C:/Users/user/Desktop/CozytechProjects/cozystream/cozystream/cozy_livestream/templates/cozy/live_session.html' /www/
